### ISSUE TITLE
Update to 3.1

### ISSUE THREAD

**Issue by edseymour** [RedHatEMEA/demobuilder#112]

**Comment by jim-minter** [comment]
Status update:

Got a very basic base 3.1 image up on demobuilder.gps.hst.ams2.redhat.com. I think the offline layer is nearly ready to commit (quite a lot of rework because of model changes & some things I wanted to fix properly), then on to the demo layer after that.

Larger outstanding tasks are:
- need to refresh JBDS and include the openshift eclipse plugin
- need to enable all the new 3.1 pieces in the build, e.g. centralised logging, metrics, etc.
- need to add demo scripting for all of above
- need to re-test the aws-ose3 scripts

**Comment by jim-minter** [comment]
All of above bar the aws-ose3 piece done - closing and moving to https://github.com/RedHatEMEA/aws-ose3/issues/7

**Comment by jim-minter** [comment]
Potential niggles?
- 100% CPU on node process?
- Unable to get network stats from pid 46289: couldn't read network stats: failure opening /proc/46289/net/dev
