### ISSUE TITLE
You may need to do this workaround to get Cluster Metrics working for pod RAM/CPU util

### ISSUE THREAD

**Issue by ffirg** [RedHatEMEA/demobuilder#121]
https://github.com/mwringe/openshift-docs/blob/node_certificates/install_config/upgrades.adoc#openshift-origin-pre-108-installation-and-kubelet-certificates

Jim - did you upgrade the existing 3.0x image to make 3.1 or was it a clean install? The problem suggests the former. My Subject Alternative Names didn't have the 10.0.2.15 node IP so heapster couldn't connect to anything.

**Comment by jim-minter** [comment]
Sorry, can we begin at the beginning?  I.e., what's the problem you're seeing / actual results / expected behaviour?  What image are you using?

The 3.1 images are installed new - there's no upgrading or anything.  Node certificates should be being regenerated correctly at image boot with the new eth0 IP address: code here:

https://github.com/RedHatEMEA/demobuilder/blob/master/layers/rhel-server-7:gui:ose-3.1/%40target/atomic-openshift-master-ipcfg.py

The 10.0.2.15 address you're mentioning - is that on the VM eth0?  If so, could that be conflicting with the SDN IP range?

I haven't seen SDN IPs in any openshift certificates so far...

**Comment by jim-minter** [comment]
issue gone inactive - feel free to re-open if needed
